# Dockerfile.airflow


FROM apache/airflow:2.7.3

RUN pip install --no-cache-dir pandas scikit-learn xgboost joblib mlflow


RUN pip install --no-cache-dir \
    scikit-learn \
    pandas \
    joblib \
    xgboost \
    mlflow

USER airflow
